// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./About.tsx')['default']
    BlogFooter: typeof import('./BlogFooter.tsx')['default']
    BlogHeader: typeof import('./BlogHeader.tsx')['default']
  }
}

export { }
