// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleTemplate: typeof import('./components/article/ArticleTemplate')['default']
    ArticleTextArea: typeof import('./components/article/ArticleTextArea')['default']
    BlogBody: typeof import('./components/BlogBody')['default']
    BlogFooter: typeof import('./components/BlogFooter')['default']
    BlogHeader: typeof import('./components/BlogHeader')['default']
    BlogListOfSelfOrOthers: typeof import('./components/BlogListOfSelfOrOthers')['default']
    EmptyPage: typeof import('./components/EmptyPage')['default']
    Layout: typeof import('./components/Layout')['default']
    MultiSkeleton: typeof import('./components/MultiSkeleton')['default']
    SvgIcon: typeof import('./components/SvgIcon')['default']
    UserInfo: typeof import('./components/user-authentication/UserInfo')['default']
    UserInput: typeof import('./components/user-authentication/UserInput')['default']
    UserLink: typeof import('./components/user-authentication/UserLink')['default']
    UserSubmitBtnTip: typeof import('./components/user-authentication/UserSubmitBtnTip')['default']
  }
}

export { }
