// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.tsx')['default']
    BlogBody: typeof import('./components/BlogBody.tsx')['default']
    BlogFooter: typeof import('./components/BlogFooter.tsx')['default']
    BlogHeader: typeof import('./components/BlogHeader.tsx')['default']
    Layout: typeof import('./components/Layout.tsx')['default']
  }
}

export { }
