// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleTemplate: typeof import('./components/article/ArticleTemplate.tsx')['default']
    ArticleTextArea: typeof import('./components/article/ArticleTextArea.tsx')['default']
    BlogBody: typeof import('./components/BlogBody.tsx')['default']
    BlogFooter: typeof import('./components/BlogFooter.tsx')['default']
    BlogHeader: typeof import('./components/BlogHeader.tsx')['default']
    BlogListOfSelfOrOthers: typeof import('./components/BlogListOfSelfOrOthers.tsx')['default']
    EmptyPage: typeof import('./components/EmptyPage.tsx')['default']
    Layout: typeof import('./components/Layout.tsx')['default']
    MultiSkeleton: typeof import('./components/MultiSkeleton.tsx')['default']
    SvgIcon: typeof import('./components/SvgIcon.tsx')['default']
    UserInfo: typeof import('./components/user-authentication/UserInfo.tsx')['default']
    UserInput: typeof import('./components/user-authentication/UserInput.tsx')['default']
    UserLink: typeof import('./components/user-authentication/UserLink.tsx')['default']
    UserSubmitBtnTip: typeof import('./components/user-authentication/UserSubmitBtnTip.tsx')['default']
  }
}

export { }
